// Package api exposes the HTTP surface: one endpoint to send a message and one
// SSE endpoint to read a reply from any cursor position.
package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/caygnus-challenge/resumable-chat/internal/hub"
	"github.com/caygnus-challenge/resumable-chat/internal/runner"
	"github.com/caygnus-challenge/resumable-chat/internal/store"
)

// replayPage bounds one database read during replay so a very long history
// cannot be loaded into memory at once.
const replayPage = 500

// heartbeat is how often an idle stream emits a ping. It is a real SSE event
// rather than a comment line, because a browser's EventSource silently drops
// comments: the client needs something observable to prove the connection is
// still alive.
const heartbeat = 5 * time.Second

// Server wires the store, the live hub and the runner behind HTTP.
type Server struct {
	store  *store.Store
	hub    *hub.Hub
	runner *runner.Runner
	// ctx is the server lifetime handed to generation goroutines.
	ctx context.Context
}

// New builds the HTTP handler.
func New(ctx context.Context, st *store.Store, h *hub.Hub, r *runner.Runner) http.Handler {
	s := &Server{store: st, hub: h, runner: r, ctx: ctx}

	mux := http.NewServeMux()
	mux.HandleFunc("POST /api/messages", s.postMessage)
	mux.HandleFunc("GET /api/runs/{runID}", s.getRun)
	mux.HandleFunc("GET /api/runs/{runID}/events", s.streamRun)
	return withCORS(mux)
}

type postMessageRequest struct {
	ConversationID string `json:"conversationId"`
	// MessageID is generated by the client so that a retried send maps to the
	// same message and the same reply instead of starting a second one.
	MessageID string `json:"messageId"`
	Text      string `json:"text"`
	// FailAfter makes the generator fail after N chunks. Demo aid for AC5.
	FailAfter int `json:"failAfter"`
}

type postMessageResponse struct {
	ConversationID string          `json:"conversationId"`
	MessageID      string          `json:"messageId"`
	RunID          string          `json:"runId"`
	Status         store.RunStatus `json:"status"`
	LastSeq        int64           `json:"lastSeq"`
	Created        bool            `json:"created"`
}

func (s *Server) postMessage(w http.ResponseWriter, r *http.Request) {
	var req postMessageRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid_json", "request body is not valid JSON")
		return
	}
	req.ConversationID = strings.TrimSpace(req.ConversationID)
	req.MessageID = strings.TrimSpace(req.MessageID)
	req.Text = strings.TrimSpace(req.Text)
	if req.ConversationID == "" || req.MessageID == "" || req.Text == "" {
		writeError(w, http.StatusBadRequest, "invalid_request", "conversationId, messageId and text are required")
		return
	}

	run, created, err := s.store.StartRun(req.ConversationID, req.MessageID, req.Text, req.FailAfter)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "store_error", err.Error())
		return
	}
	if created {
		s.runner.Start(s.ctx, run, req.Text)
	}

	writeJSON(w, http.StatusAccepted, postMessageResponse{
		ConversationID: run.ConversationID,
		MessageID:      run.UserMessageID,
		RunID:          run.ID,
		Status:         run.Status,
		LastSeq:        run.LastSeq,
		Created:        created,
	})
}

func (s *Server) getRun(w http.ResponseWriter, r *http.Request) {
	run, err := s.store.Run(r.PathValue("runID"))
	if errors.Is(err, store.ErrRunNotFound) {
		writeError(w, http.StatusNotFound, "run_not_found", "no such run")
		return
	}
	if err != nil {
		writeError(w, http.StatusInternalServerError, "store_error", err.Error())
		return
	}
	writeJSON(w, http.StatusOK, run)
}

// streamRun is the resumable stream.
//
// Order of operations matters and is the heart of this exercise:
//  1. validate the cursor against durable state,
//  2. subscribe to live events *before* reading history,
//  3. replay stored events after the cursor,
//  4. switch to live, skipping anything replay already covered.
//
// Doing (2) before (3) means an event produced during the replay is buffered
// rather than lost; the skip in (4) means it is not delivered twice.
func (s *Server) streamRun(w http.ResponseWriter, r *http.Request) {
	runID := r.PathValue("runID")
	run, err := s.store.Run(runID)
	if errors.Is(err, store.ErrRunNotFound) {
		writeError(w, http.StatusNotFound, "run_not_found", "no such run")
		return
	}
	if err != nil {
		writeError(w, http.StatusInternalServerError, "store_error", err.Error())
		return
	}

	after, err := cursor(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid_cursor", err.Error())
		return
	}
	// A cursor ahead of durable history means the client is talking about a
	// run this server never had, or state it invented. Say so explicitly
	// instead of streaming a stream with a silent hole in it.
	if after > run.LastSeq {
		writeJSON(w, http.StatusConflict, errorBody{
			Error:   "cursor_unavailable",
			Message: "cursor is ahead of the stored history; restart from lastSeq",
			LastSeq: run.LastSeq,
			Status:  run.Status,
		})
		return
	}

	flusher, ok := w.(http.Flusher)
	if !ok {
		writeError(w, http.StatusInternalServerError, "streaming_unsupported", "response writer cannot flush")
		return
	}
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no")
	w.WriteHeader(http.StatusOK)

	// Step 2: subscribe before reading history.
	sub := s.hub.Subscribe(runID)
	defer sub.Close()

	// A control frame, deliberately without an id, so it never moves the
	// client's cursor. It carries the run state the client shows in the UI.
	writeFrame(w, flusher, 0, "state", stateFrame{Status: run.Status, LastSeq: run.LastSeq})

	// Step 3: replay.
	sent := after
	for {
		events, err := s.store.EventsAfter(runID, sent, replayPage)
		if err != nil {
			log.Printf("run %s: replay failed: %v", runID, err)
			return
		}
		if len(events) == 0 {
			break
		}
		for _, ev := range events {
			writeFrame(w, flusher, ev.Seq, ev.Type, ev)
			sent = ev.Seq
			if ev.Terminal() {
				return // history already ends here; nothing live can follow
			}
		}
	}

	// A run that was already terminal when we read it can never gain another
	// event, so replay was the whole story. Waiting for live delivery here
	// would hold the connection open forever for a client that reconnects at
	// the very end of a finished run.
	if run.Status.Terminal() {
		return
	}

	// Step 4: live.
	ticker := time.NewTicker(heartbeat)
	defer ticker.Stop()
	for {
		select {
		case <-r.Context().Done():
			return // the client went away; its cursor is its own business
		case <-s.ctx.Done():
			return // the server is shutting down; let the connection close
		case <-ticker.C:
			writeFrame(w, flusher, 0, "ping", stateFrame{Status: store.StatusRunning, LastSeq: sent})
		case ev, open := <-sub.Events():
			if !open {
				if sub.Lagged() {
					// We dropped this connection to protect the generator.
					// Tell the client to reconnect from its cursor.
					writeFrame(w, flusher, 0, "reset", errorBody{
						Error:   "subscriber_lagged",
						Message: "connection fell behind; reconnect from your cursor",
						LastSeq: sent,
					})
				}
				return
			}
			if ev.Seq <= sent {
				continue // already delivered during replay
			}
			writeFrame(w, flusher, ev.Seq, ev.Type, ev)
			sent = ev.Seq
			if ev.Terminal() {
				return
			}
		}
	}
}

type stateFrame struct {
	Status  store.RunStatus `json:"status"`
	LastSeq int64           `json:"lastSeq"`
}

// cursor reads the resume position from the query string, falling back to the
// SSE Last-Event-ID header that browsers send on an automatic reconnect.
func cursor(r *http.Request) (int64, error) {
	raw := r.URL.Query().Get("after")
	if raw == "" {
		raw = r.Header.Get("Last-Event-ID")
	}
	if raw == "" {
		return 0, nil
	}
	after, err := strconv.ParseInt(raw, 10, 64)
	if err != nil || after < 0 {
		return 0, fmt.Errorf("cursor must be a non-negative integer, got %q", raw)
	}
	return after, nil
}

// writeFrame emits one SSE frame. A seq of 0 means "control frame": no id is
// written, so the browser will not resume from it.
func writeFrame(w http.ResponseWriter, f http.Flusher, seq int64, event string, payload any) {
	body, err := json.Marshal(payload)
	if err != nil {
		log.Printf("marshal %s frame: %v", event, err)
		return
	}
	if seq > 0 {
		fmt.Fprintf(w, "id: %d\n", seq)
	}
	fmt.Fprintf(w, "event: %s\ndata: %s\n\n", event, body)
	f.Flush()
}

type errorBody struct {
	Error   string          `json:"error"`
	Message string          `json:"message"`
	LastSeq int64           `json:"lastSeq,omitempty"`
	Status  store.RunStatus `json:"status,omitempty"`
}

func writeError(w http.ResponseWriter, code int, kind, message string) {
	writeJSON(w, code, errorBody{Error: kind, Message: message})
}

func writeJSON(w http.ResponseWriter, code int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	if err := json.NewEncoder(w).Encode(payload); err != nil {
		log.Printf("write response: %v", err)
	}
}

// withCORS lets the Vite dev server on another port talk to this API. A real
// deployment would serve both from one origin and drop this.
func withCORS(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Last-Event-ID")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next.ServeHTTP(w, r)
	})
}
