// The message box and the three stream controls.
//
// Button availability is derived from the live connection and run state, never
// from local guesses: Send while nothing is running, Drop only while a stream
// is open, Reconnect only while it is not.

import type { RunView } from "../useRun";

const maxLength = 2000;

interface ComposerProps {
  view: RunView;
  draft: string;
  onDraftChange: (value: string) => void;
  failMidway: boolean;
  onFailMidwayChange: (value: boolean) => void;
  onSend: () => void;
  onDrop: () => void;
  onReconnect: () => void;
}

export function Composer({
  view,
  draft,
  onDraftChange,
  failMidway,
  onFailMidwayChange,
  onSend,
  onDrop,
  onReconnect,
}: ComposerProps) {
  const streaming = view.status === "running";
  const canSend = draft.trim().length > 0 && !streaming;
  // Drop only makes sense on a live connection. Reconnect only makes sense for
  // an unfinished run whose connection is down or being re-established.
  const canDrop = view.connection === "connected";
  const canReconnect =
    view.runId !== null &&
    view.status === "running" &&
    (view.connection === "disconnected" || view.connection === "reconnecting");

  return (
    <section className="card composer" aria-label="Your message">
      <h2 className="card-title">Your message</h2>

      <textarea
        id="message"
        value={draft}
        maxLength={maxLength}
        rows={3}
        onChange={(event) => onDraftChange(event.target.value)}
        placeholder="Type anything. The answer is generated by the server."
      />
      <p className="char-count mono">
        {draft.length} / {maxLength}
      </p>

      <div className="composer-actions">
        <button type="button" className="primary" disabled={!canSend} onClick={onSend}>
          <span aria-hidden="true">➤</span> Send
        </button>
        <button type="button" onClick={onDrop} disabled={!canDrop}>
          <span aria-hidden="true">⦸</span> Drop connection
        </button>
        <button type="button" onClick={onReconnect} disabled={!canReconnect}>
          <span aria-hidden="true">⟳</span> Reconnect
        </button>
        <label className="toggle">
          <input
            type="checkbox"
            checked={failMidway}
            onChange={(event) => onFailMidwayChange(event.target.checked)}
          />
          Fail generator after 12 chunks
        </label>
      </div>
    </section>
  );
}
